name: .NET

env:
  configuration: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    permissions:
      actions: none

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump environment
        run: printenv | sort

  build:

    services:
      mongodb:
        image: mongo:5.0.3
        ports:
        - 8081:8081
        - 27017:27017
        
    runs-on: ubuntu-latest

    env:
      RepositoryUrl: https://github.com/${{ github.repository }}
      source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      # version: 0.0.1-beta.${{ github.run_number }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # full history

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x
        source-url: ${{ env.source-url }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool restore

    - name: Build
      run: dotnet build --no-restore -p:RepositoryUrl=${{ env.RepositoryUrl }} /bl

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --no-build -p:RepositoryUrl=${{ env.RepositoryUrl }} /bl:LogFile=msbuild-pack.binlog

    - name: Publish the package to GPR
      run: dotnet nuget push "Verify.MongoDB/bin/Release/*.nupkg" --source ${{ env.source-url }} -k ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main'

    - name: Build logs
      uses: actions/upload-artifact@v2.3.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: '*.binlog'