name: .NET

env:
  configuration: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    permissions:
      actions: none

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump environment
        run: printenv | sort

  build:

    services:
      mongodb:
        image: mongo:5.0.3
        ports:
        - 8081:8081
        - 27017:27017
        
    runs-on: ubuntu-latest

    outputs:
      GitBuildVersionSimple: ${{ steps.gitversion.outputs.GitBuildVersionSimple }}

    env:
      RepositoryUrl: https://github.com/${{ github.repository }}
      source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # full history

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x
        source-url: ${{ env.source-url }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: dotnet build -p:RepositoryUrl=${{ env.RepositoryUrl }} /bl

    # Set GitBuildVersionSimple output variable
    - name: gitversion
      id: gitversion
      run: |
        echo "::set-output name=GitBuildVersionSimple::$GitBuildVersionSimple" 

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish the package to GPR
      run: dotnet nuget push "Verify.MongoDB/bin/Release/*.nupkg" --source ${{ env.source-url }} -k ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main'

    - name: Build logs
      uses: actions/upload-artifact@v2.3.1
      with:
        name: logs
        # A file, directory or wildcard pattern that describes what to upload
        path: '*.binlog'

    - name: NuGet Package
      uses: actions/upload-artifact@v2.3.1
      with:
        name: nupkg
        # A file, directory or wildcard pattern that describes what to upload
        path: 'Verify.MongoDB/bin/Release/*.nupkg'

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [build]

    if: github.ref == 'refs/heads/main' # Running this job only for main branch
    steps:
      - uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ needs.build.outputs.GitBuildVersionSimple }}

      - uses: actions/download-artifact@v2
          
      - name: Display structure of downloaded files
        run: ls -R 

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Upload assets
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "./nupkg/**/*.nupkg"
          delete_file: "*.nupkg"
          overwrite: true
          release_id: ${{ steps.create_release.outputs.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        