name: .NET

env:
  configuration: Release
  source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    permissions:
      actions: none

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump environment
        run: printenv | sort

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      RepositoryUrl: https://github.com/${{ github.repository }}

    outputs:
      GitBuildVersionSimple: ${{ steps.gitversion.outputs.GitBuildVersionSimple }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            6.0.x
            8.0.x
            10.0.x
          source-url: ${{ env.source-url }}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: dotnet build /bl

      # Set GitBuildVersionSimple output variable
      - name: gitversion
        id: gitversion
        run: |
          echo "GitBuildVersionSimple=$GitBuildVersionSimple" >> $GITHUB_OUTPUT

      - name: Dump environment
        run: printenv | sort

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build logs
        uses: actions/upload-artifact@v5
        with:
          name: logs
          # A file, directory or wildcard pattern that describes what to upload
          path: "*.binlog"

      - name: NuGet Package
        uses: actions/upload-artifact@v5
        with:
          name: nupkg
          # A file, directory or wildcard pattern that describes what to upload
          path: "Verify.MongoDB/bin/Release/*.nupkg"

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    if: github.ref == 'refs/heads/main' # Running this job only for main branch
    steps:
      - uses: actions/checkout@v5

      - uses: release-drafter/release-drafter@v6
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ needs.build.outputs.GitBuildVersionSimple }}

      - uses: actions/download-artifact@v6

      - name: Display structure of downloaded files
        run: ls -R

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Upload assets
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "./nupkg/**/*.nupkg"
          delete_file: "*.nupkg"
          overwrite: true
          release_id: ${{ steps.create_release.outputs.id }}

  publish_to_gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v6
        with:
          name: nupkg

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish to GitHub Packages
        run: dotnet nuget push *.nupkg --source ${{ env.source-url }} -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate          